### ISSUE TITLE
Add job descriptions directly on the page

### ISSUE THREAD

**Issue by jonbesga** [F1Jobs/client#2]
Congratulations on the website. I discovered it today in [/r/Python](https://www.reddit.com/r/Python/comments/94u68s/i_spent_the_last_week_building_an_opensource/).

It would be a nice feature to have the job descriptions directly on the page. This way visitors wouldn't have to visit the employer websites unless they want to apply.

**Comment by aydwi** [comment]
There are certain factors to consider before of if I implement it.

1. Getting job descriptions is somewhat more unreliable than getting just the job titles.
2. It will affect the load time of the website as significantly more data will be transferred.
3. I'm not sure if it will have a net positive effect. A job title gives you enough information to decide whether you are interested or not, and if you are, it is just a click away. Not much effort and efficient design. I wouldn't want to mess with it unless I have a solid reason to do so.

I'll think and discuss about thoroughly this before I think about implementing it. Thanks for the suggestion, I appreciate it.

**Comment by aydwi** [comment]
@jonbesga I've put some thought into this, and I think for now I will let things remain as they are. However, in the future, if things change and I (and others) feel that this feature is needed, I'll reopen this issue. I'm closing this issue for now due to the reasons mentioned above. Thanks once again for your suggestion.
